Final_Project/Controllers/CarritoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Final_Project.Models;

namespace Final_Project.Controllers
{
    public class CarritoController : Controller
    {
        private readonly CarritoDbContex _context;

        public CarritoController(CarritoDbContex context)
        {
            _context = context;
        }

        // GET: Carrito
        public async Task<IActionResult> Index(DataProductos data)
        {
            @ViewData["Contadora"]= data.Precio;
            return View(await _context.DATA.ToListAsync());
        }

        // GET: Carrito/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dataProductos = await _context.DATA
                .FirstOrDefaultAsync(m => m.Id == id);
            if (dataProductos == null)
            {
                return NotFound();
            }

            return View(dataProductos);
        }

        // GET: Carrito/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Carrito/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Foto,Nombre,Descripcion,Cantidad,Estado,Categoria,Precio")] DataProductos dataProductos)
        {
            if (ModelState.IsValid)
            {
                _context.Add(dataProductos);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(dataProductos);
        }

        // GET: Carrito/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dataProductos = await _context.DATA.FindAsync(id);
            if (dataProductos == null)
            {
                return NotFound();
            }
            return View(dataProductos);
        }

        // POST: Carrito/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Foto,Nombre,Descripcion,Cantidad,Estado,Categoria")] DataProductos dataProductos)
        {
            if (id != dataProductos.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(dataProductos);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DataProductosExists(dataProductos.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(dataProductos);
        }

        // GET: Carrito/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dataProductos = await _context.DATA
                .FirstOrDefaultAsync(m => m.Id == id);
            if (dataProductos == null)
            {
                return NotFound();
            }

            return View(dataProductos);
        }

        // POST: Carrito/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var dataProductos = await _context.DATA.FindAsync(id);
            _context.DATA.Remove(dataProductos);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DataProductosExists(int id)
        {
            return _context.DATA.Any(e => e.Id == id);
        }
    }
}

Final_Project/Controllers/OrdenesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Final_Project.Data;
using Final_Project.Models;

namespace Final_Project.Controllers
{
    public class OrdenesController : Controller
    {
        private readonly OrdenesDbContext _context;

        public OrdenesController(OrdenesDbContext context)
        {
            _context = context;
        }

        // GET: Ordenes
        public async Task<IActionResult> Index()
        {
            return View(await _context.Orden.ToListAsync());
        }

        public async Task<IActionResult> Compras(string Buscar)
        {
            var movies = from m in _context.Orden select m;

            if (!String.IsNullOrEmpty(Buscar))
            {
                movies = movies.Where(s => s.Estado.Contains(Buscar));
            }

            return View(await movies.ToListAsync());
        }
      

        // GET: Ordenes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dataProductos = await _context.Orden
                .FirstOrDefaultAsync(m => m.Id == id);
            if (dataProductos == null)
            {
                return NotFound();
            }

            return View(dataProductos);
        }

        // GET: Ordenes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Ordenes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Foto,Nombre,Descripcion,Cantidad,Estado,Categoria,Precio,NombreOrden,NombreCliente,ApellidoCliente,Direccion,Correo,Telefono,Latitud,Longitud")] DataProductos dataProductos)
        {
            if (ModelState.IsValid)
            {
                _context.Add(dataProductos);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(dataProductos);
        }

        // GET: Ordenes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dataProductos = await _context.Orden.FindAsync(id);
            if (dataProductos == null)
            {
                return NotFound();
            }
            return View(dataProductos);
        }

        // POST: Ordenes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Foto,Nombre,Descripcion,Cantidad,Estado,Categoria,Precio,NombreOrden,NombreCliente,ApellidoCliente,Direccion,Correo,Telefono,Latitud,Longitud")] DataProductos dataProductos)
        {
            if (id != dataProductos.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(dataProductos);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DataProductosExists(dataProductos.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(dataProductos);
        }

        // GET: Ordenes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dataProductos = await _context.Orden
                .FirstOrDefaultAsync(m => m.Id == id);
            if (dataProductos == null)
            {
                return NotFound();
            }

            return View(dataProductos);
        }

        // POST: Ordenes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var dataProductos = await _context.Orden.FindAsync(id);
            _context.Orden.Remove(dataProductos);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DataProductosExists(int id)
        {
            return _context.Orden.Any(e => e.Id == id);
        }
    }
}

Final_Project/Controllers/RolController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Final_Project.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Final_Project.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class RolController : Controller
    {

        private readonly RoleManager<IdentityRole> roleManager;

        public RolController(RoleManager<IdentityRole> roleManager)
        {
            this.roleManager = roleManager;
        }

        public IActionResult Agregar()
        {

            return View();
        }
        
        [HttpPost]
        public async Task<IActionResult> Agregar(Roles role)
        {
            var roleExist = await roleManager.RoleExistsAsync(role.Rol);
            if (!roleExist)
            {
                var result = await roleManager.CreateAsync(new IdentityRole(role.Rol));
            }
            return View();
        }


        public IActionResult Index()
        {
            return View();
        }
    }
}

Final_Project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Final_Project</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />


    @*Iconos*@
    <link href="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css" rel="stylesheet">
    <script src="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js"></script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

    @*Mapa*@
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css" />
    <script src="https://unpkg.com/leaflet@1.6.0/dist/leaflet.js"></script>

    <style>
        #map {
            position: absolute;
            height: 600px;
            width: 1080px;
        }

        #slider {
            width: 500px;
            height: 500px;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Slider" asp-action="Inicio">Epay</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Productos" asp-action="Catalogo">Catalago</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Ordenes" asp-action="Compras">Mi historial de compras</a>
                                </li>
                            }
                        }
                                @{

                                    if (User.IsInRole("Administrador"))
                                    {
                                        <li class="nav-item dropdown">
                                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                Administración
                                            </a>
                                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                                <a class="nav-link text-dark" asp-area="" asp-controller="Rol" asp-action="Agregar">Añadir Rol</a>
                                                <a class="nav-link text-dark" asp-area="" asp-controller="Productos" asp-action="Create">Añadir Artículo</a>
                                                <a class="nav-link text-dark" asp-area="" asp-controller="Slider" asp-action="Create">Añadir Slider</a>
                                                <div class="dropdown-divider"></div>
                                                <a class="nav-link text-dark" asp-area="" asp-controller="Ordenes" asp-action="Index">Ordenes</a>
                                            </div>
                                        </li>
                                    }
                                }

                                @if (User.Identity.IsAuthenticated)
                                {
                                    {
                                        <div class="text-right">
                                            <li class="nav-item">
                                                <a class="nav-link text-dark" asp-area="" asp-controller="Carrito" asp-action="Index"><i class="large material-icons">shopping_cart</i></a>
                                            </li>
                                        </div>
                                    }
                                }
                            </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Final_Project - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>